// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebShop.API.Database;

namespace WebShop.API.Migrations
{
    [DbContext(typeof(WebShopContext))]
    [Migration("20211003074730_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebShop.API.Database.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Floor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZipCityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ZipCityId");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Danmark",
                            CustomerId = 1,
                            Floor = "1. TH",
                            Number = 222,
                            StreetName = "testvej",
                            ZipCityId = 2100
                        },
                        new
                        {
                            Id = 2,
                            Country = "Danmark",
                            CustomerId = 1,
                            Floor = "2. TV",
                            Number = 34,
                            StreetName = "Nyborggade",
                            ZipCityId = 2100
                        });
                });

            modelBuilder.Entity("WebShop.API.Database.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sport",
                            Picture = "jakob-owens-j5kEQ1JLqZk-unsplash.jpg"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Party",
                            Picture = "michael-discenza-MxfcoxycH_Y-unsplash.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Housekeeping",
                            Picture = "ashwini-chaudhary-Iu6parQAO-U-unsplash.jpg"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hangout",
                            Picture = "nathan-dumlao-71u2fOofI-U-unsplash.jpg"
                        });
                });

            modelBuilder.Entity("WebShop.API.Database.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Christian",
                            LastName = "Jørgensen",
                            MiddleName = "Møller",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("WebShop.API.Database.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Path = "Here/Perfect",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            Path = "Someware/Nice",
                            ProductId = 1
                        });
                });

            modelBuilder.Entity("WebShop.API.Database.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BillingAddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ShipmentAddressId")
                        .HasColumnType("int");

                    b.Property<int?>("ShippingAddressId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BillingAddressId");

                    b.HasIndex("ShippingAddressId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("WebShop.API.Database.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("CurrentPrice")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItem");
                });

            modelBuilder.Entity("WebShop.API.Database.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "MAKE TESTS GREAT AGIAN",
                            Name = "TestProduct1",
                            Price = 100
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "MAKE TESTS GREAT AGIAN",
                            Name = "TestProduct2",
                            Price = 200
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "MAKE TESTS GREAT AGIAN",
                            Name = "TestProduct3",
                            Price = 300
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "MAKE TESTS GREAT AGIAN",
                            Name = "TestProduct4",
                            Price = 300
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "MAKE TESTS GREAT AGIAN",
                            Name = "TestProduct5",
                            Price = 300
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "MAKE TESTS GREAT AGIAN",
                            Name = "TestProduct6",
                            Price = 300
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "MAKE TESTS GREAT AGIAN",
                            Name = "TestProduct7",
                            Price = 300
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "MAKE TESTS GREAT AGIAN",
                            Name = "TestProduct8",
                            Price = 300
                        });
                });

            modelBuilder.Entity("WebShop.API.Database.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@admin.dk",
                            Password = "admin",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Email = "user@user.dk",
                            Password = "user",
                            Role = 1
                        });
                });

            modelBuilder.Entity("WebShop.API.Database.Entities.ZipCity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ZipCity");

                    b.HasData(
                        new
                        {
                            Id = 2000,
                            City = "Frederiksberg"
                        },
                        new
                        {
                            Id = 2100,
                            City = "Østerbro"
                        });
                });

            modelBuilder.Entity("WebShop.API.Database.Entities.Address", b =>
                {
                    b.HasOne("WebShop.API.Database.Entities.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebShop.API.Database.Entities.ZipCity", "ZipCity")
                        .WithMany()
                        .HasForeignKey("ZipCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("ZipCity");
                });

            modelBuilder.Entity("WebShop.API.Database.Entities.Customer", b =>
                {
                    b.HasOne("WebShop.API.Database.Entities.User", "User")
                        .WithOne("Customer")
                        .HasForeignKey("WebShop.API.Database.Entities.Customer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebShop.API.Database.Entities.Image", b =>
                {
                    b.HasOne("WebShop.API.Database.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebShop.API.Database.Entities.Order", b =>
                {
                    b.HasOne("WebShop.API.Database.Entities.Address", "BillingAddress")
                        .WithMany()
                        .HasForeignKey("BillingAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebShop.API.Database.Entities.Address", "ShippingAddress")
                        .WithMany()
                        .HasForeignKey("ShippingAddressId");

                    b.Navigation("BillingAddress");

                    b.Navigation("ShippingAddress");
                });

            modelBuilder.Entity("WebShop.API.Database.Entities.OrderItem", b =>
                {
                    b.HasOne("WebShop.API.Database.Entities.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebShop.API.Database.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebShop.API.Database.Entities.Product", b =>
                {
                    b.HasOne("WebShop.API.Database.Entities.Category", "Category")
                        .WithMany("products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WebShop.API.Database.Entities.Category", b =>
                {
                    b.Navigation("products");
                });

            modelBuilder.Entity("WebShop.API.Database.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("WebShop.API.Database.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("WebShop.API.Database.Entities.Product", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("WebShop.API.Database.Entities.User", b =>
                {
                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
